/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	kubeopbot_v1alpha1 "github.com/maleck13/kubeop-bot/pkg/apis/kubeopbot/v1alpha1"
	clientset "github.com/maleck13/kubeop-bot/pkg/client/clientset_generated/clientset"
	internalinterfaces "github.com/maleck13/kubeop-bot/pkg/client/informers_generated/externalversions/internalinterfaces"
	v1alpha1 "github.com/maleck13/kubeop-bot/pkg/client/listers_generated/kubeopbot/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// AlertInformer provides access to a shared informer and lister for
// Alerts.
type AlertInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AlertLister
}

type alertInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewAlertInformer constructs a new informer for Alert type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAlertInformer(client clientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.KubeopbotV1alpha1().Alerts(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.KubeopbotV1alpha1().Alerts(namespace).Watch(options)
			},
		},
		&kubeopbot_v1alpha1.Alert{},
		resyncPeriod,
		indexers,
	)
}

func defaultAlertInformer(client clientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewAlertInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *alertInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubeopbot_v1alpha1.Alert{}, defaultAlertInformer)
}

func (f *alertInformer) Lister() v1alpha1.AlertLister {
	return v1alpha1.NewAlertLister(f.Informer().GetIndexer())
}
